name: "Alternus"
description: ""

url: "/alternus.gultij.org"
rawcode_url: "https://raw.githubusercontent.com/alvarezp/alternus.gultij.org/gh-pages/"

markdown: rdiscount
permalink: pretty

collections:
- colaboradores
