name: "Alternus"
description: ""

url: "http://alvarezp.github.io/alternus"
rawcode_url: "https://raw.githubusercontent.com/alvarezp/alternus/master/"

markdown: rdiscount
permalink: pretty

collections:
- colaboradores
