name: "Alternus"
description: ""

url: "http://alternus.gultij.org"
rawcode_url: "https://raw.githubusercontent.com/gultij/alternus.gultij.org/gh-pages/"

markdown: rdiscount
permalink: pretty

collections:
- colaboradores
